#!/bin/sh

## Usage:
## pod=pod <other variables> $0
##

. ./bash_include 

# fork to expect-lite
expect-lite c=`basename $0` el=expect-lite log=$log d=$PWD r=localhost\
    pod_address="$pod_address" pod=$pod timeout=$timeout
exit $?

*LOG $log
@$timeout

; === Connect to $pod ===
>screen gatttool -I --listen -b $pod_address
*/[$pod_address][LE]>/
-<Usage
>>^A
>H
<logfile
>connect
-<Error
-<connect error
<Connection successful
>>^A
>^D
>

# save screen id
>screen -list | grep pts | sort | head -1
+$myscreen=([0-9]+\.pts.[0-9]+.[a-z\- 0-9]+)
>

##------------------------------------------------------------------##

; ==== Test "get volt" ====
>rm $SCREENLOG
>echo -n "get volt" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ==== Verify "get volt" e.g. "Vbat =  5.67" ====
>egrep -a Notification $SCREENLOG | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<Vbat

##------------------------------------------------------------------##

; ==== Test "get time" ====
>rm $SCREENLOG
>echo -n "get time" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ==== Verify "get time" e.g. "UTC time: 17:53:47" ====
>egrep -a Notification $SCREENLOG | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<UTC time

##------------------------------------------------------------------##

; ==== Test "get date" ====
>rm $SCREENLOG
>echo -n "get date" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ==== Verify "get date" e.g. "UTC date: 2018/10/02" ====
>egrep -a Notification $SCREENLOG | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<UTC date

; ==== Cleanup ====
>>screen -S $myscreen -X stuff 'exit\015'
