#!/bin/sh

## usage:
##   $0 <POD>
##


pod_name=${1:-testpod}
pod_address=`fgrep -his $pod_name podnames | awk '{print $1}'`
echo " ==== Setup `basename $0` on $pod_name ==== "

timeout=${timeout:-10}
export EL_DELAY_WAIT_FOR_HOST=${timeout}000
export EL_SHELL=/bin/sh

# fork to expect-lite
expect-lite c=`basename $0` el=expect-lite log=${pod_name}-`basename $0`.log d=$PWD r=localhost\
    pod_address="$pod_address" pod_name=$pod_name timeout=$timeout
exit $?

*LOG
@$timeout

; === Connect to $pod_name ===
*/[$pod_address][LE]>/
>screen -Logfile screen.log gatttool -I --listen -b $pod_address
-<Usage
>>^A
>H
>connect
-<Error
-<connect error
<Connection successful
>>^A
>^D
>

# save screen id
>screen -list | grep pts | sort | head -1
+$myscreen=([0-9]+\.pts.[0-9]+.[a-z\- 0-9]+)
>

##------------------------------------------------------------------##

; ==== Test "get volt" ====
>cp /dev/null screen.log
>echo -n "get volt" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
:2
>

; ==== Verify "get volt" e.g. "Vbat =  5.67" ====
>
>egrep -a Notification screen.log | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<Vbat

##------------------------------------------------------------------##

; ==== Test "get time" ====
>cp /dev/null screen.log
>echo -n "get time" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
:2
>

; ==== Verify "get time" e.g. "UTC time: 17:53:47" ====
>
>egrep -a Notification screen.log | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<UTC time

##------------------------------------------------------------------##

; ==== Test "get date" ====
>cp /dev/null screen.log
>echo -n "get date" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
:2
>

; ==== Verify "get date" e.g. "UTC date: 2018/10/02" ====
>
>egrep -a Notification screen.log | cut -f7 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
<UTC date

; ==== Cleanup ====
#>screen -S $myscreen -X stuff 'exit\015'
>killall screen
