#!/bin/sh

./test-command $pod "get volt" "Vbat"
if [ $? -ne 0 ]; then exit $?; fi
sleep 2

./test-command $pod "get time" "UTC time"
if [ $? -ne 0 ]; then exit $?; fi
sleep 2

./test-command $pod "get date" "UTC date"
if [ $? -ne 0 ]; then exit $?; fi
sleep 2

