#!/bin/sh

##
## Default parameterss for testing. Set on the command line to change, e.g.:
##
## $ ssid=Barnacle pswd=clearwater timeout=100 ./runtest tests/wifi_setup
##

export EL_pod=${pod:-testpod}
export EL_address=`fgrep -his $EL_pod podnames | awk '{print $1}'`
export EL_mode=${mode:-Sense}

export EL_fw_env=${env:-prod}
export EL_fw_index=${index:-9.1}
export EL_fw_version=${version:-v9.1.14}
export EL_fw_bleversion=${bleversion:-9}

export EL_ssid=${ssid:-WG2}
export EL_pswd=${pswd:-clearwater}
export EL_ssid_len=`echo -n $EL_ssid | wc -c`
export EL_pswd_len=`echo -n $EL_pswd | wc -c`

export EL_gallons=${gal:-10000}
#export EL_fc_target=${fc_target:-3.0}
#export EL_fc_limit=${fc_limit:-1.0}
#export EL_ph_target=${ph:-7.5}
export EL_pump_hour=${pump_hour:-3}
export EL_pump_min=${pump_minute:-10}
#export EL_flow_delta=${flow:-9.0}

##------------------------------------------------------------------##

export EL_timeout=${timeout:-30}
export EL_delay=${delay:-120}
export EL_DELAY_WAIT_FOR_HOST=${EL_timeout}00
export EL_SCREENRC=screenrc
export EL_SHELL=/bin/sh
export PATH=./tests:./tests/local:./tests/cloud:./tests/pool:./tests/diag:$PATH

# run each argument as a test script
for test in $*; do
    export EL_log=logs/${EL_pod}-`basename $test`.log
    export EL_SCREENLOG=logs/${EL_pod}-`basename $test`-ble.log
    export EL_testname=${EL_pod}-`basename $test`

    $test

    case $? in
        0) echo PASS: "$EL_testname" ;;
        *) echo FAIL: "$EL_testname" ;;
    esac

    sleep 10

done
