#!/bin/sh

##
## Defaults for test scripts. Set these on the command-line to change.
##

test=${test:-basic_info}

# variables exported as constants to test scripts
export EL_pod=${pod:-testpod}
export EL_address=`fgrep -his $EL_pod podnames | awk '{print $1}'`

export EL_fw_env=${env:-prod}
export EL_fw_index=${index:-9.1}
export EL_fw_version=${version:-v9.1}
export EL_fw_bleversion=${bleversion:-9}

export EL_ssid=${ssid:-WG2}
export EL_pswd=${pswd:-clearwater}
export EL_ssid_len=`echo -n $EL_ssid | wc -c`
export EL_pswd_len=`echo -n $EL_pswd | wc -c`

export EL_timeout=${timeout:-20}
export EL_log=logs/${EL_pod}-$test.log
export EL_INFINITE_LOOP=20
export EL_DELAY_WAIT_FOR_HOST=${EL_timeout}00
export EL_DYN_VAR_PROMPT=1
export EL_SHELL=/bin/sh

export EL_SCREENRC=screenrc
export EL_SCREENLOG=logs/${EL_pod}-$test-gatt.log

./tests/$test
