#!/bin/sh

## Usage:
## pod=pod <other variables> $0 <COMMAND>
##

command=$1
hex_command=`echo -n $* | xxd -ps`; shift
#result=${result:-\$}

. ./bash_include

# fork to expect-lite
expect-lite c=`basename $0` el=expect-lite log=$log d=$PWD r=localhost \
    pod_address="$pod_address" hex_command=$hex_command result="$result" \
    command="$command" timeout=$timeout
exit $?

*LOG $log
@$timeout

; ==== Test: $command ====
*/[$pod_address][LE]>/
>gatttool --listen -b $pod_address --char-write-req --handle=0x001b --value=$hex_command
-<Usage
-<Error
-<connect error
<Characteristic value was written successfully
>^C

; ==== Output ====
>egrep -a '^Notification' $log | cut -f2 -d: | sed 's/^/0a/g' | xxd -r -ps; echo
-<Please try again
-<Unknown
#<<$result
>>
