#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

$json=logs/${EL_mfg}-${EL_testname}.json
>rm -f $json

>podrec $EL_pod $json
<<"StatusCode": 200

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Verify fw series e.g. "$EL_fw_index" ============
>cat $json | jo -a -p | fgrep fwSeries | awk '{print $2}'
<<"$EL_fw_index",

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Verify FW version "$EL_fw_version" ============
>cat $json | jo -a -p | fgrep fwUpdateVersion | awk '{print $2}'
<"$EL_fw_version.*",

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Verify BLE version "$EL_fw_bleversion" ============
>cat $json | jo -a -p | fgrep fwBleVersion | awk '{print $2}'
<<"$EL_fw_bleversion",

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
