#!/usr/bin/env expect-lite

##
## regular cloud check with no firmware download or log upload
##

? $test_in_progress != 1 ? ~tests/connect.inc

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "cloud check" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "cloud check" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 43 6c 6f 75 64 20 63 68 65 63 6b 20 64 6f 6e 65
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify e.g. "Cloud check done" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
-<SSID NOT FOUND
-<Upload OK
-<Bytes to go
<Cloud check done

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
