#!/usr/bin/env expect-lite

$json=logs/${EL_mfg}-${EL_testname}.json
>rm -f $json

? $test_in_progress != 1 ? ~tests/connect.inc

$test_in_progress=1
~tests/cloud/cloud_check
$test_in_progress=0

>podrec $EL_pod $json
<<"StatusCode": 200

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test pool gallons $EL_gallons ============
>cp /dev/null $EL_BLELOG
>echo -n "get poolgal" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 47 61 6c 6c 6f 6e 73 3a
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify pod pool gallons $EL_gallons ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<Gallons: $EL_gallons

; ============ WaterGuru $EL_pod $EL_testname: Verify cloud pool gallons $EL_gallons ============
>cat $json | jo -a -p | fgrep sizeGal | awk '{print $2}'
<<$EL_gallons,

# ; ============ WaterGuru $EL_pod $EL_testname: Test measure time ============

# XXX TODO: fix s3log function for test user
# 1. BLE "timers show"
# 2. BLE "zlog"
# 3. AWS s3log
# 4. compare two completely different formats [facepalm]

? $test_in_progress != 1 ? ~tests/cleanup.inc
