#!/usr/bin/env expect-lite

##-------------------------------------------------------------------##
# XXX setup a firmware download via OpsGuru
##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/connect.inc

; ============ WaterGuru $EL_pod $EL_testname: "remote MCU firmware upgrade" ============
@$EL_DELAY_WAIT_FOR_HOST
>cp /dev/null $EL_BLELOG
>echo -n "cloud check" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73
>disconnect
>>^A
>^D
>
@$EL_timeout

; ============ WaterGuru $EL_pod $EL_testname: Verify e.g. "Bytes to go: 0 bytes" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
-<SSID NOT FOUND
<Bytes to go: 0 bytes

:$EL_delay

##-------------------------------------------------------------------##

$test_in_progress=1
~tests/version_check
$test_in_progress=0

##-------------------------------------------------------------------##
# this will fail if there is another download

$test_in_progress=1
~tests/cloud/cloud_check
$test_in_progress=0

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
