#!/usr/bin/env expect-lite

; ~~~~~~~~>  Verify firmware versions <~~~~~~~~

# - connect to console (serial or BLE), and power supply, logging each
? $test_in_progress != 1 ? ~tests/connect.inc

# - defaults could be taken from parameters.sh or runteest
$TEST_CMD=version
$LOG_CMD=zlog
$LOG_READ=cat

# - translate to hex if we have an address
? $EL_ble != "" ? [
$TEST_CMD="char-write-req 0x001b `echo -n "$TEST_CMD" | xxd -ps`\015"
$LOG_CMD="char-write-req 0x001b `echo -n "$LOG_CMD" | xxd -ps`\015"
$LOG_READ=dehex
]

# - send the TEST_CMD to the DUT, 5 sec delay
>screen -r $EL_testname -X stuff "$TEST_CMD"
:5

# - verify console output
>$LOG_READ $EL_BLELOG
<TI_VERS $EL_fw_bleversion
<$EL_fw_version
]

# - upload the log and verify result contents #issue
~tests/wifi/log_upload
# XXX now download and check the log

# - verify power consumption from screen logs
# XXX read back the power supply log for this test... check.

? $test_in_progress != 1 ? ~tests/cleanup.inc
