#!/usr/bin/env expect-lite

~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get volt" ============
>cat /dev/null > $SCREENLOG
>echo -n "get volt" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 56 62 61 74 20 3d 20
>>^A
>^D
>

; ============ $EL_testname: Verify "get volt" e.g. "Vbat =  5.67" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Vbat =  [5-6]\.[0-9][0-9]

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get time" ============
>cat /dev/null > $SCREENLOG
>echo -n "get time" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 74 69 6d 65 3a 20
>>^A
>^D
>

; ============ $EL_testname: Verify "get time" e.g. "UTC time: 17:53:47" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<UTC time: [1-9][0-9]?:[0-5][0-9]?:[0-5][0-9]?

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get date" ============
>cat /dev/null > $SCREENLOG
>echo -n "get date" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 64 61 74 65 3a 20
>>^A
>^D
>

; ============ $EL_testname: Verify "get date" e.g. "UTC date: 2018/10/02" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<UTC date: 201[8-9]/[1-9][0-9]?/[1-9][0-9]?

##------------------------------------------------------------------##

~cleanup.inc
