#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> $EL_testname: Check "get volt" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n get volt | xxd -ps`\015"
>dehex $EL_BLELOG | grep volt

]::[

# serial
>screen -r $EL_testname -X stuff "\015\015"
>screen -r $EL_testname -X stuff "get volt\015"
>cat $EL_BLELOG | grep volt

]

<.*volt [5-6]\.[0-9][0-9]

; ~~~~~~~~> $EL_testname: Test "get resist" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `get resist | xxd -ps`\015"
>dehex $EL_BLELOG | tail | grep resist

]::[

# Serial
>screen -r $EL_testname -X stuff "get resist\015"
>tail $EL_BLELOG | grep resist

]

<.*resist [0-3]\.[0-9][0-9]

; ~~~~~~~~> $EL_testname: Test "get time" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `get time | xxd -ps`\015"
>dehex $EL_BLELOG | tail | grep time

]::[

# Serial
>screen -r $EL_testname -X stuff "get time\015"
>tail $EL_BLELOG | grep time

]
<UTC time: [0-9][0-9]?:[0-5][0-9]?:[0-5][0-9]?

; ~~~~~~~~> $EL_testname: Test "get date" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `get date | xxd -ps`\015"
>dehex $EL_BLELOG | tail | grep date

]::[

# Serial
>screen -r $EL_testname -X stuff "get date\015"
>tail $EL_BLELOG | grep date

]

<UTC date: 202[1-9]/[0-9][0-9]?/[0-9][0-9]?

? $test_in_progress != 1 ? ~tests/cleanup.inc
