#!/usr/bin/env expect-lite

~connect.inc

##------------------------------------------------------------------##

; ============ Test download "fw dwld ble" ============
@120
>rm $SCREENLOG
>echo -n "fw dwld ble" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>^M
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73 
>>^A
>^D
>
@$EL_timeout

; ============ Verify download "fw dwld ble" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Bytes to go

##------------------------------------------------------------------##

; ============ Test "fw ble" ============
>rm $SCREENLOG
>echo -n "fw ble" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>>exit
>

:30

##------------------------------------------------------------------##

~connect.inc

##------------------------------------------------------------------##

; ============ Test "restart" ============
>rm $SCREENLOG
>echo -n "restart" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>>exit
>

; ============ Verify "restart" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Restarting

:30

##------------------------------------------------------------------##

~connect.inc

##------------------------------------------------------------------##

; ============ Test BLE "version" ============
>rm $SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify BLE "version" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<TI_VERS = $bleversion
>

##------------------------------------------------------------------##

; ============ Cleanup ============
>>rm $SCREENLOG
>screen -r $myscreen
>>^A
>h
>^D
#>>screen -S $myscreen -X stuff 'exit\015'
