#!/usr/bin/env expect-lite

##
## regular cloud check with no firmware download or log upload
##

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> $EL_testname: cloud check <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n cloud | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "cloud\015"
>cat $EL_BLELOG | tail

]

-<Cloud check failed
<Cloud check passed

? $test_in_progress != 1 ? ~tests/cleanup.inc
