#!/usr/bin/env expect-lite

##
## connect to a power supply and log current
##

*NOINFO
#*TIMESTAMP
*/\n/

>>picocom --nolock --noreset --echo --omap crcrlf --imap lfcrlf $EL_power
<<Terminal ready
>*IDN?
>*IDN?
<B&K Precision, 9201(.*)\n
>>SYST:REM
>>VOLT 6.0
>>CURR 2.0
>>OUTP 1

$count=0
[ $count < 3
    >>MEAS:CURR?
    <[0-9](.*)\n
    :$EL_power_rate
]     

