#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~connect.inc
$test_in_progress=1

##-------------------------------------------------------------------##

; ============ $EL_testname: "zlog" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "zlog" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 70 6c 6f 61 64 20 4f 4b 3b 20 6c 6f 67 20 72 65 73 65 74 
>>^A
>^D
>

; ============ $EL_testname: Verify e.g. "Upload OK; log reset" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
-<SSID NOT FOUND
<Upload OK; log reset

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~cleanup.inc
