#!/usr/bin/env expect-lite

##
## upload the log now
##

? $test_in_progress != 1 ? [
*~cleanup.inc
~tests/connect.inc
]

; ~~~~~~~~> $EL_testname: "$log" <~~~~~~~~

? $EL_serial == NONE ? [

>screen -S $EL_testname -X stuff "char-write-req 0x001b `echo -n zlog | xxd -ps`\015"

]::[

>screen -S $EL_testname -X stuff '\$log\015'
]

:45

? $EL_serial == NONE ? [
>dehex $EL_BLELOG | tail
]::[
>cat $EL_BLELOG | tail
]

-<Upload failed
-<Log empty
<.*Log dump OK
>^C

? $test_in_progress != 1 ? ~tests/cleanup.inc
