#!/usr/bin/env expect-lite

~setup.inc

##------------------------------------------------------------------##

; ============ Test set "fw env" ============
>rm $SCREENLOG
>echo -n "fw env $env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify set "fw env" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env set to \'$env\'

##------------------------------------------------------------------##

; ============ Test show "fw env" ============
>rm $SCREENLOG
>echo -n "fw env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify show "fw env" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env = $env

##------------------------------------------------------------------##

; ============ Test set "fw index" ============
>rm $SCREENLOG
>echo -n "fw index $index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify set "fw index" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$index

##------------------------------------------------------------------##

; ============ Test show "fw index" ============
>rm $SCREENLOG
>echo -n "fw index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify show "fw index" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$index

##------------------------------------------------------------------##

; ============ Test download "fw dwld" ============
@90
>rm $SCREENLOG
>echo -n "fw dwld" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>^M
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73 
>>^A
>^D
>
@$EL_timeout

; ============ Verify download "fw dwld" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Bytes to go: 0 bytes

##------------------------------------------------------------------##

; ============ Test "fw inst" ============
>rm $SCREENLOG
>echo -n "fw inst" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>exit
>

; ============ Verify "fw inst" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Restarting

:sleep 60

##------------------------------------------------------------------##

~setup.inc

##------------------------------------------------------------------##

; ============ Test "version" ============
>rm $SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ Verify "version" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$version

##------------------------------------------------------------------##

; ============ Cleanup ============
>screen -r $myscreen
>>^A
>h
>^D
#>>screen -S $myscreen -X stuff 'exit\015'
