#!/usr/bin/env expect-lite

~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: set "fw env" ============
>cat /dev/null > $SCREENLOG
>echo -n "fw env $EL_fw_env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 65 6e 76 20 73 65 74 20 74 6f 20
>>^A
>^D
>

; ============ $EL_testname: Verify set "fw env" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env set to \'$EL_fw_env\'

##------------------------------------------------------------------##

; ============ $EL_testname: show "fw env" ============
>cat /dev/null > $SCREENLOG
>echo -n "fw env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 65 6e 76 20 3d 20
>>^A
>^D
>

; ============ $EL_testname: Verify show "fw env" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env = $EL_fw_env

##------------------------------------------------------------------##

; ============ $EL_testname: set "fw index" ============
>cat /dev/null > $SCREENLOG
>echo -n "fw index $EL_fw_index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify set "fw index" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$EL_fw_index

##------------------------------------------------------------------##

; ============ $EL_testname: show "fw index" ============
>cat /dev/null > $SCREENLOG
>echo -n "fw index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify show "fw index" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$EL_fw_index

##------------------------------------------------------------------##

; ============ $EL_testname: download "fw dwld" ============
@90
>cat /dev/null > $SCREENLOG
>echo -n "fw dwld" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>^M
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73 
>>^A
>^D
>
@$EL_timeout

; ============ $EL_testname: Verify download "fw dwld" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Bytes to go: 0 bytes

##------------------------------------------------------------------##

; ============ $EL_testname: "fw inst" ============
>cat /dev/null > $SCREENLOG
>echo -n "fw inst" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>exit
>

; ============ $EL_testname: Verify "fw inst" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Restarting

:45

##------------------------------------------------------------------##

~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: "version" ============
>cat /dev/null > $SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify "version" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$EL_fw_version

##------------------------------------------------------------------##

~cleanup.inc
