#!/usr/bin/env expect-lite

~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: set "fw env" ============
>rm $SCREENLOG
>echo -n "fw env $env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify set "fw env" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env set to \'$env\'

##------------------------------------------------------------------##

; ============ $EL_testname: show "fw env" ============
>rm $SCREENLOG
>echo -n "fw env" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify show "fw env" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<env = $env

##------------------------------------------------------------------##

; ============ $EL_testname: set "fw index" ============
>rm $SCREENLOG
>echo -n "fw index $index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify set "fw index" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$index

##------------------------------------------------------------------##

; ============ $EL_testname: show "fw index" ============
>rm $SCREENLOG
>echo -n "fw index" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify show "fw index" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$index

##------------------------------------------------------------------##

; ============ $EL_testname: download "fw dwld" ============
@90
>rm $SCREENLOG
>echo -n "fw dwld" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>^M
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73 
>>^A
>^D
>
@$EL_timeout

; ============ $EL_testname: Verify download "fw dwld" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Bytes to go

##------------------------------------------------------------------##

; ============ $EL_testname: "fw inst" ============
>rm $SCREENLOG
>echo -n "fw inst" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>exit
>

; ============ $EL_testname: Verify "fw inst" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<Restarting

:sleep 60

; ============ Re-connect to $pod ============

~connect.inc

; ============ $EL_testname: "version" ============
>rm $SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify "version" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$version


; ============ Cleanup ============
>>rm $SCREENLOG
>screen -r $myscreen
>>^A
>h
>^D
#>>screen -S $myscreen -X stuff 'exit\015'
