#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> Check firmware version <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n version | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "\015"
>screen -r $EL_testname -X stuff "version\015"
>tail $EL_BLELOG

]

<.*WI-FI_VERS $EL_fw_wifiversion
<.*TI_VERS $EL_fw_bleversion
<.*$EL_fw_version

]

? $test_in_progress != 1 ? ~tests/cleanup.inc
