#!/usr/bin/env expect-lite

~connect.inc

$version=$EL_fw_version

##------------------------------------------------------------------##

; ============ $EL_testname: "version" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ $EL_testname: Verify "version" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<$version

##------------------------------------------------------------------##

~cleanup.inc
