#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: "version" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 54 49 5f 56 45 52 53
>>^A
>^D
>

; ============ $EL_testname: Verify "version" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<$EL_fw_version

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~cleanup.inc

