#!/usr/bin/env expect-lite

##
## check installed firmware version(s)
##

? $test_in_progress != 1 ? [
*~cleanup.inc
~tests/connect.inc
]

; ~~~~~~~~> Check firmware version <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req $EL_handle `echo -n version | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "version\015"
>cat $EL_BLELOG | tail

]

#<.*WI-FI_VERS $EL_fw_wifiversion
#<.*TI_VERS $EL_fw_bleversion
<.*$EL_fw_version

? $test_in_progress != 1 ? ~tests/cleanup.inc
