#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> $EL_testname: "ssid reset" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n ssid reset | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "ssid reset\015"
>cat $EL_BLELOG | tail

]

<ssid chars = 0

; ~~~~~~~~> $EL_testname: "ssid save" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n ssid save | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "ssid save\015"
>cat $EL_BLELOG | tail

]

<ssid saved

; ~~~~~~~~> $EL_testname: "ssid show" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n ssid show | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "ssid show\015"
>cat $EL_BLELOG | tail

]

<ssid =\s+\n

; ~~~~~~~~> $EL_testname: "pswd reset" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n pswd reset | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "pswd reset\015"
>cat $EL_BLELOG | tail

]

<pswd chars = 0

; ~~~~~~~~> $EL_testname: "pswd save" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n pswd save | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "pswd save\015"
>cat $EL_BLELOG | tail

]

<pswd saved

; ~~~~~~~~> $EL_testname: "pswd show" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n pswd show | xxd -ps`\015"
>dehex $EL_BLELOG | tail

]::[

# Serial
>screen -r $EL_testname -X stuff "pswd show\015"
>cat $EL_BLELOG | tail

]

<pswd =\s+\n

? $test_in_progress != 1 ? ~tests/cleanup.inc

