#!/usr/bin/env expect-lite

~connect.inc

##-------------------------------------------------------------------##

; ============ Test "ssid reset" ============
>rm $SCREENLOG
>echo -n "ssid reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "ssid reset" e.g. "ssid chars = 0" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid chars = 0

##-------------------------------------------------------------------##

; ============ Test "ssid save" ============
>rm $SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "ssid save" e.g. "ssid saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ Test "ssid set" ============
>rm $SCREENLOG
>echo -n "ssid set $ssid" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "ssid set $ssid" e.g. "ssid chars = $ssid_len" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid chars = $ssid_len

##-------------------------------------------------------------------##

; ============ Test "ssid save" ============
>rm $SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "ssid save" e.g. "ssid saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ Test "ssid show" ============
>rm $SCREENLOG
>echo -n "ssid show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "ssid show" e.g. "$ssid" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$ssid

##-------------------------------------------------------------------##

; ============ Test "pswd reset" ============
>rm $SCREENLOG
>echo -n "pswd reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "pswd reset" e.g. "pswd chars = 0" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd chars = 0

##-------------------------------------------------------------------##

; ============ Test "pswd save" ============
>rm $SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "pswd save" e.g. "pswd saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ Test "pswd set" ============
>rm $SCREENLOG
>echo -n "pswd set $pswd" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "pswd set $pswd" e.g. "pswd chars = $pswd_len" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd chars = $pswd_len

##-------------------------------------------------------------------##

; ============ Test "pswd save" ============
>rm $SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "pswd save" e.g. "pswd saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ Test "pswd show" ============
>rm $SCREENLOG
>echo -n "pswd show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D

; ============ Verify "pswd show" e.g. "$pswd" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$pswd

##-------------------------------------------------------------------##

; ============ Test "wifi test" ============
>rm $SCREENLOG
@40
>echo -n "wifi test" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 57 49 2d 46 49 20 4f 4b 00 00 00 00 00 00 00 00 00 00 00 00
>>^A
>^D

; ============ Verify "wifi test" e.g. "WI-FI OK" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
-<SSID NOT FOUND
<WI-FI OK

##-------------------------------------------------------------------##

; ============ Cleanup ============
>>rm $SCREENLOG
>screen -r $myscreen
>>^A
>h
>^D
#>>screen -S $myscreen -X stuff 'exit\015'
