#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~connect.inc

##-------------------------------------------------------------------##

$test_in_progress=1
~tests/wifi_reset
$test_in_progress=0

##-------------------------------------------------------------------##

; ============ $EL_testname: "ssid set" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "ssid set $EL_ssid" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 63 68 61 72 73 20 3d
>>^A
>^D
>

; ============ $EL_testname: Verify "ssid set $EL_ssid" e.g. "ssid chars = $EL_ssid_len" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<ssid chars = $EL_ssid_len

##-------------------------------------------------------------------##

; ============ $EL_testname: "ssid save" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 73 61 76 65 64
>>^A
>^D
>

; ============ $EL_testname: Verify "ssid save" e.g. "ssid saved" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ $EL_testname: "ssid show" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "ssid show" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 3d
>>^A
>^D
>

; ============ $EL_testname: Verify "ssid show" e.g. "$EL_ssid" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<$EL_ssid

##-------------------------------------------------------------------##

; ============ $EL_testname: "pswd set" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "pswd set $EL_pswd" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 63 68 61 72 73 20 3d
>>^A
>^D
>

; ============ $EL_testname: Verify "pswd set $EL_pswd" e.g. "pswd chars = $EL_pswd_len" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<pswd chars = $EL_pswd_len

##-------------------------------------------------------------------##

; ============ $EL_testname: "pswd save" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 73 61 76 65 64
>>^A
>^D
>

; ============ $EL_testname: Verify "pswd save" e.g. "pswd saved" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ $EL_testname: "pswd show" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "pswd show" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 3d
>>^A
>^D
>

; ============ $EL_testname: Verify "pswd show" e.g. "$EL_pswd" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
<$EL_pswd

##-------------------------------------------------------------------##

; ============ $EL_testname: "wifi test" ============
>cp /dev/null $EL_SCREENLOG-tmp
>echo -n "wifi test" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 57 49 2d 46 49 20 4f 4b
>>^A
>^D
>

; ============ $EL_testname: Verify "wifi test" e.g. "WI-FI OK" ============
>dehex $EL_SCREENLOG-tmp
-<Please try again
-<Unknown
-<SSID NOT FOUND
<WI-FI OK

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~cleanup.inc

