#!/usr/bin/env expect-lite

~connect.inc

##-------------------------------------------------------------------##

; ============ Test "ssid reset" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid reset" e.g. "ssid chars = 0" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid chars = 0

##-------------------------------------------------------------------##

; ============ Test "ssid save" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid save" e.g. "ssid saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ Test "ssid set" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid set $EL_ssid" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid set $EL_ssid" e.g. "ssid chars = $EL_ssid_len" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid chars = $EL_ssid_len

##-------------------------------------------------------------------##

; ============ Test "ssid save" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid save" e.g. "ssid saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ Test "ssid show" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid show" e.g. "$EL_ssid" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$EL_ssid

##-------------------------------------------------------------------##

; ============ Test "pswd reset" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd reset" e.g. "pswd chars = 0" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd chars = 0

##-------------------------------------------------------------------##

; ============ Test "pswd save" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd save" e.g. "pswd saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ Test "pswd set" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd set $EL_pswd" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd set $EL_pswd" e.g. "pswd chars = $EL_pswd_len" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd chars = $EL_pswd_len

##-------------------------------------------------------------------##

; ============ Test "pswd save" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd save" e.g. "pswd saved" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ Test "pswd show" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd show" e.g. "$EL_pswd" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
<$EL_pswd

##-------------------------------------------------------------------##

; ============ Test "wifi test" ============
>cat /dev/null > $SCREENLOG
@40
>echo -n "wifi test" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 57 49 2d 46 49 20 4f 4b 00 00 00 00 00 00 00 00 00 00 00 00
>>^A
>^D
>

; ============ Verify "wifi test" e.g. "WI-FI OK" ============
>dehex $SCREENLOG
-<Please try again
-<Unknown
-<SSID NOT FOUND
<WI-FI OK

##-------------------------------------------------------------------##

~cleanup.inc
