#!/usr/bin/env expect-lite

~connect.inc

##-------------------------------------------------------------------##

; ============ Test "ssid reset" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid reset" e.g. "ssid chars = 0" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid chars = 0

##-------------------------------------------------------------------##

; ============ Test "ssid save" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid save" e.g. "ssid saved" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ Test "ssid show" ============
>cat /dev/null > $SCREENLOG
>echo -n "ssid show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "ssid show" e.g. "ssid =" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<ssid =

##-------------------------------------------------------------------##

; ============ Test "pswd reset" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd reset" e.g. "pswd chars = 0" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd chars = 0

##-------------------------------------------------------------------##

; ============ Test "pswd save" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd save" e.g. "pswd saved" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ Test "pswd show" ============
>cat /dev/null > $SCREENLOG
>echo -n "pswd show" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>>^A
>^D
>

; ============ Verify "pswd show" e.g. "pswd =" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
<pswd =

##-------------------------------------------------------------------##

; ============ Test "wifi test" ============
>cat /dev/null > $SCREENLOG
@40
>echo -n "wifi test" | xxd -ps
+$cmd=\n(.*)
>screen -r $myscreen
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 53 53 49 44 20 4e 4f 54 20 46 4f 55 4e 44 00 00 00 00 00 00 
>>^A
>^D
>

; ============ Verify "wifi test" e.g. "SSID NOT FOUND" ============
>
>dehex $SCREENLOG
-<Please try again
-<Unknown
-<WI-FI OK
<SSID NOT FOUND

##-------------------------------------------------------------------##

~cleanup.inc
