#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##------------------------------------------------------------------##

$test_in_progress=1
~tests/version_check
$test_in_progress=0

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get volt" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "get volt" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 56 62 61 74 20 3d 20
>
>>^A
>^D
>

; ============ $EL_testname: Verify "get volt" e.g. "Vbat =  5.67" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<Vbat =  [5-6]\.[0-9][0-9]

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get time" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "get time" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 74 69 6d 65 3a 20
>
>>^A
>^D
>

; ============ $EL_testname: Verify "get time" e.g. "UTC time: 17:53:47" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<UTC time: [0-9][0-9]?:[0-5][0-9]?:[0-5][0-9]?

##------------------------------------------------------------------##

; ============ $EL_testname: Test "get date" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "get date" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 64 61 74 65 3a 20
>
>>^A
>^D
>

; ============ $EL_testname: Verify "get date" e.g. "UTC date: 2019/01/07" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<UTC date: 201[8-9]/[0-9][0-9]?/[0-9][0-9]?

##------------------------------------------------------------------##

; ============ $EL_testname: Test "pod rdid" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "pod rdid" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 50 4f 44 20 49 44 20 3d
>
>>^A
>^D
>

; ============ $EL_testname: Verify pod ID e.g. $EL_podid ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<POD ID = [1-9][0-9]+

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
