#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: download "fw dwld ble" ============
@$EL_DELAY_WAIT_FOR_HOST
>cp /dev/null $EL_SCREENLOG
>echo -n "fw dwld ble" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73
>
>>^A
>^D
>
@$EL_timeout

; ============ WaterGuru $EL_pod $EL_testname: Verify download "fw dwld ble" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<Bytes to go: 0 bytes

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "fw ble" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "fw ble" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>>disconnect
>>^A
>^D
>

:$EL_delay

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "restart" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "restart" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>connect
-<Error
-<connect error
-<connect: Device or resource busy (16)
<Connection successful
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 52 65 73 74 61 72 74 69 6e 67 2e 2e 2e
>>disconnect
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "restart" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<Restarting

:$EL_timeout

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: BLE "version" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>connect
-<Error
-<connect error
-<connect: Device or resource busy (16)
<Connection successful
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 54 49 5f 56 45 52 53 20 3d
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify BLE "$EL_fw_bleversion" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<TI_VERS = $EL_fw_bleversion

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
