#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "zlog" ============
@$EL_delay
>cp /dev/null $EL_BLELOG
>echo -n "zlog" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 70 6c 6f 61 64 20 4f 4b 3b 20 6c 6f 67 20 72 65 73 65 74 
>
>>^A
>^D
>
@$EL_timeout

; ============ WaterGuru $EL_pod $EL_testname: Verify e.g. "Upload OK; log reset" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
-<SSID NOT FOUND
-<Upload failed
<Upload OK; log reset

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
