#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "sensor mode" ============
>cp /dev/null $EL_BLELOG
>echo -n "set mode" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 50 6f 64 20 4d 6f 64 65 20 3d 20 53 65 6e 73 65
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify E.g. "Pod Mode = $EL_fw_mode" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<Pod Mode = $EL_fw_mode

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc

