#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~connect.inc

##------------------------------------------------------------------##

; ============ $EL_testname: fw version ============
>cp /dev/null $EL_SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 54 49 5f 56 45 52 53
>
>>^A
>^D
>

; ============ $EL_testname: Verify fw version "$EL_fw_version" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<$EL_fw_version

##------------------------------------------------------------------##

; ============ $EL_testname: BLE version ============
>cp /dev/null $EL_SCREENLOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 54 49 5f 56 45 52 53
>
>>^A
>^D
>

; ============ $EL_testname: Verify BLE version "$EL_fw_bleversion" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<TI_VERS = $EL_fw_bleversion

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~cleanup.inc
