#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "ssid reset" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "ssid reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 63 68 61 72 73 20 3d 20 30
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "ssid reset" e.g. "ssid chars = 0" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<ssid chars = 0

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "ssid save" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "ssid save" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
#<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 73 61 76 65 64
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "ssid save" e.g. "ssid saved" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<ssid saved

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "ssid show" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "ssid show" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 73 73 69 64 20 3d 
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "ssid show" e.g. "ssid =" ============
>
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<ssid =\s+\n

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "pswd reset" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "pswd reset" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 63 68 61 72 73 20 3d 20 30
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "pswd reset" e.g. "pswd chars = 0" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<pswd chars = 0

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "pswd save" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "pswd save" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 73 61 76 65 64
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "pswd save" e.g. "pswd saved" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<pswd saved

##-------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "pswd show" ============
>cp /dev/null $EL_SCREENLOG
>echo -n "pswd show" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 70 73 77 64 20 3d
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "pswd show" e.g. "pswd =" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<pswd =\s+\n

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc

