#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> $EL_testname: Check "get volt" <~~~~~~~~

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n get volt | xxd -ps`\015"
>dehex $EL_BLELOG | tail -f

]::[

# serial
>screen -r $EL_testname -X stuff "\015\015"
>screen -r $EL_testname -X stuff "get volt\015"
>cat #EL_BLELOG | tail -f

]

<.*Vbat =  [5-6]\.[0-9][0-9]

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "get resist" ============
>cp /dev/null $EL_BLELOG
>echo -n "get resist" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 72 65 73 69 73 74 61 6e 63 65
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "get resist" e.g. "resistance 1.80" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<resistance [1-2]\.[0-9][0-9]

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "get time" ============
>cp /dev/null $EL_BLELOG
>echo -n "get time" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 74 69 6d 65 3a 20
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "get time" e.g. "UTC time: 17:53:47" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<UTC time: [0-9][0-9]?:[0-5][0-9]?:[0-5][0-9]?

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "get date" ============
>cp /dev/null $EL_BLELOG
>echo -n "get date" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 55 54 43 20 64 61 74 65 3a 20
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "get date" e.g. "UTC date: 2019/01/07" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<UTC date: 202[1-9]/[0-9][0-9]?/[0-9][0-9]?

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
