#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: set "fw env" ============
>cp /dev/null $EL_BLELOG
>echo -n "fw env $EL_fw_env" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 65 6e 76 20 73 65 74 20 74 6f 20
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify set "fw env" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<env set to \'$EL_fw_env\'

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: show "fw env" ============
>cp /dev/null $EL_BLELOG
>echo -n "fw env" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify show "fw env" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<.*\$env $EL_fw_env

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: set "fw index" ============
>cp /dev/null $EL_BLELOG
>echo -n "fw index $EL_fw_index" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
<Notification
<Notification
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify set "fw index" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<$EL_fw_index

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: show "fw index" ============
>cp /dev/null $EL_BLELOG
>echo -n "fw index" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify show "fw index" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<$EL_fw_index

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: download "fw dwld" ============
@$EL_DELAY_WAIT_FOR_HOST
>cp /dev/null $EL_BLELOG
>echo -n "fw dwld" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>^M
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 42 79 74 65 73 20 74 6f 20 67 6f 3a 20 30 20 62 79 74 65 73
>
>>^A
>^D
>
@$EL_timeout

; ============ WaterGuru $EL_pod $EL_testname: Verify download "fw dwld" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<Bytes to go: 0 bytes

:$EL_delay

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "fw inst" ============
>cp /dev/null $EL_BLELOG
>echo -n "fw inst" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 52 65 73 74 61 72 74 69 6e 67 2e 2e 2e
>disconnect
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "fw inst" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<Restarting

:$EL_delay

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: "version" ============
>cp /dev/null $EL_BLELOG
>echo -n "version" | xxd -ps
+$cmd=\n(.*)
>screen -r $EL_testname
>connect
-<Error
-<connect error
-<connect: Device or resource busy (16)
<Connection successful
>char-write-req 0x001b $cmd
<Characteristic value was written successfully
<Notification handle = 0x001b value: 54 49 5f 56 45 52 53
>
>>^A
>^D
>

; ============ WaterGuru $EL_pod $EL_testname: Verify "$EL_fw_version" ============
>dehex $EL_BLELOG
-<Please try again
-<Unknown
<$EL_fw_version

##------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc

