#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

##-------------------------------------------------------------------##

# boilerplate
# ; ============ WaterGuru $EL_pod $EL_testname: "set log $EL_testname" ============
# >cp /dev/null $EL_BLELOG
# >echo -n "set log $EL_testname" | xxd -ps
# +$cmd=\n(.*)
# >screen -r $EL_testname
# >char-write-req 0x001b $cmd
# <Characteristic value was written successfully
# <Notification handle = 0x001b value: 4c 4f 47 47 45 44 3a
# >
# >>^A
# >^D
# >
# @$EL_timeout
# 
# ; ============ WaterGuru $EL_pod $EL_testname: Verify e.g. "LOGGED: $EL_testname" ============
# >dehex $EL_BLELOG
# -<Please try again
# -<Unknown
# <LOGGED: $EL_testname

##-------------------------------------------------------------------##

? $test_in_progress != 1 ? ~tests/cleanup.inc
