#!/usr/bin/env expect-lite

? $test_in_progress != 1 ? ~tests/connect.inc

; ~~~~~~~~> $EL_testname: "zlog" ============

? $EL_serial == NONE ? [

# BLE
>screen -r $EL_testname -X stuff "char-write-req 0x001b `echo -n zlog | xxd -ps`\015"
:$EL_timeout
>dehex $EL_BLELOG

]::[

# Serial
>screen -r $EL_testname -X stuff "\015\015"
>screen -r $EL_testname -X stuff "zlog\015"
:$EL_timeout
>tail -f $EL_BLELOG 

]

-<Please try again
-<Unknown
-<SSID NOT FOUND
-<Upload failed
<Upload OK; log reset

? $test_in_progress != 1 ? ~tests/cleanup.inc
