#!/usr/bin/env expect-lite

*NOINFO
*NOFAIL
~tests/connect.inc
*~../cleanup.inc


; -+-+-+-> WaterGuru $EL_pod $EL_testname: Test temperature current

$testitem=tempCurrent
$testcond=0
$testvalue=NONE
$teststatus=WARN

>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n get temp | xxd -ps`\015"
:4

>tail -10 $EL_POWERLOG > logs/$EL_pod-$EL_testname-sample.log
>dos2unix logs/$EL_pod-$EL_testname-sample.log
>cat logs/$EL_pod-$EL_testname-sample.log
>egrep -v '0.00[0-1]|1e' logs/$EL_pod-$EL_testname-sample.log | wc -l
+$count=\n([0-9].*)\n
; $count samples over 10 sec.

>egrep -v '0.000|1e' logs/$EL_pod-$EL_testname-sample.log | sed 's/^/+ /g' | xargs echo 0 | bc
+$total=\n(.*)\n
>awk "BEGIN { print 0$total / $count }"
+$testvalue=\n([0-9].*)\n
; $average current $testvalue

? $testvalue > 0.012 ? $teststatus=FAIL
? $testvalue < 0.007 ? $teststatus=FAIL :: $teststatus=PASS
>

; $EL_testname $testitem $teststatus
>echo `date +%C%y%m%d:%H%m%S`, $EL_testname, $EL_mfg, $EL_user, $testitem, $testcond, $testvalue, $teststatus | tee -a $EL_stationlog
>


; -+-+-+-> WaterGuru $EL_pod $EL_testname: Test version current
$testitem=versionCurrent
$testcond=0
$testvalue=NONE
$teststatus=WARN

>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n version | xxd -ps`\015"
:4

>tail -10 $EL_POWERLOG > logs/$EL_pod-$EL_testname-sample.log
>dos2unix logs/$EL_pod-$EL_testname-sample.log
>cat logs/$EL_pod-$EL_testname-sample.log
>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | wc -l
+$count=\n([0-9].*)\n
; $count samples over 10 sec.

>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | sed 's/^/+ /g' | xargs echo 0 | bc
+$total=\n(.*)\n
>awk "BEGIN { print 0$total / $count }"
+$testvalue=\n([0-9].*)\n
; $average current $testvalue

? $testvalue > 0.0619 ? $teststatus=FAIL :: $teststatus=PASS
? $testvalue < 0.0590 ? $teststatus=FAIL :: $teststatus=PASS
>

; $EL_testname $testitem $teststatus
>echo `date +%C%y%m%d:%H%m%S`, $EL_testname, $EL_mfg, $EL_user, $testitem, $testcond, $testvalue, $teststatus | tee -a $EL_stationlog
>


; -+-+-+-> WaterGuru $EL_pod $EL_testname: Test pad motor current
$testitem=padMotorCurrent
$testcond=0
$testvalue=NONE
$teststatus=WARN

; running... (30s)

>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n pad dist 10000 | xxd -ps`\015"
:30
>tail -60 $EL_POWERLOG > logs/$EL_pod-$EL_testname-sample.log
>dos2unix logs/$EL_pod-$EL_testname-sample.log
>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | wc -l
+$count=\n([0-9].*\n)
; $count samples over 30 sec.

>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | sed 's/^/+ /g' | xargs echo 0 | bc
+$total=\n([0-9].*\n)
>awk "BEGIN { print $total / $count }"
+$testvalue=\n([0-9].*\n)
; $average current $testvalue

? $testvalue < 0.4 ? $teststatus=PASS :: $teststatus=FAIL
? $testvalue < 0.2 ? $teststatus=WARN
? $testvalue < 0.1 ? $teststatus=FAIL
; $EL_testname $testitem $teststatus

>echo `date +%C%y%m%d:%H%m%S`, $EL_testname, $EL_mfg, $EL_user, $testitem, $testcond, $testvalue, $teststatus | tee -a $EL_stationlog
>

; -+-+-+-> WaterGuru $EL_pod $EL_testname: Test RGB current
$testitem=RGBCurrent
$testcond=0
$testvalue=NONE
$teststatus=WARN

; running... (25s)

>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n 820B46FF | xxd -ps`\015"
:25
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n 80 | xxd -ps`\015"
:5

>tail -60 $EL_POWERLOG > logs/$EL_pod-$EL_testname-sample.log
>dos2unix logs/$EL_pod-$EL_testname-sample.log
>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | wc -l
+$count=\n([0-9].*)\n
; $count samples over 30 sec.

>egrep -v '0.00|1e' logs/$EL_pod-$EL_testname-sample.log | sed 's/^/+ /g' | xargs echo 0 | bc
+$total=\n(.*)\n
>awk "BEGIN { print 0$total / $count }"
+$testvalue=\n([0-9].*)\n
; $average current $testvalue

? $testvalue < 0.018 ? $teststatus=WARN
? $testvalue > 0.024 ? $teststatus=FAIL :: $teststatus=PASS
; $EL_testname $testitem $teststatus

; $EL_testname $testitem $teststatus
>echo `date +%C%y%m%d:%H%m%S`, $EL_testname, $EL_mfg, $EL_user, $testitem, $testcond, $testvalue, $teststatus | tee -a $EL_stationlog
>

~tests/cleanup.inc
