#!/usr/bin/env expect-lite

~tests/connect.inc
# *NOINFO

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "get temp" ============
#>cp /dev/null $EL_SCREENLOG
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n get temp | xxd -ps`\015"
:10

; ============ WaterGuru $EL_pod $EL_testname: Verify "get temp" e.g. "water temp = 67.0" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<water temp = [1-9][0-9]*\.[0-9]

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: test BLE and MCU version ============
#>cp /dev/null $EL_SCREENLOG
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n version | xxd -ps`\015"
:5

; ============ WaterGuru $EL_pod $EL_testname: Verify BLE and MCU firmware versions ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<TI_VERS = $EL_fw_bleversion
<$EL_fw_version

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "pad dist 10000" ============
#>cp /dev/null $EL_SCREENLOG
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n pad dist 10000 | xxd -ps`\015"
:40

; ============ WaterGuru $EL_pod $EL_testname: Verify "pad dist 10000" output ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<vbat =
<retcode =
<mAs=

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: Test "820B46FF (RGB lights)" ============
#>cp /dev/null $EL_SCREENLOG
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n 820B46FF | xxd -ps`\015"
:20
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n 80 | xxd -ps`\015"
:5

; ============ WaterGuru $EL_pod $EL_testname: Verify "820B46FF (RGB lights)" e.g. "EXECUTED 0x820B46FF" ============
>dehex $EL_SCREENLOG
-<Please try again
-<Unknown
<EXECUTED 0x820B46FF

##------------------------------------------------------------------##

; ============ WaterGuru $EL_pod $EL_testname: log test end and cleanup ============
>screen -r $EL_testname -S -X stuff "char-write-req 0x001b `echo -n set log end | xxd -ps`\015"
>screen -r $EL_testname -S -X stuff 'exit\015'
>killall screen
